---
language: node_js
dist: trusty
node_js:
- '10.14'
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
  - "/^v?[0-9]+.[0-9]+.[0-9]+(-.*)?$/"

cache:
  directories:
  - "$HOME/.npm"
jobs:
  include:
  - stage: test
    script:
    - npm run lint
    - npm run test
    after_success: npm run coverage
